export const ApiConstants = {
    refreshToken: 'api/Account/RefreshToken',
    changePassword: 'api/Account/ChangePassword',
    login: 'api/Account/Login',
    sendForgotPasswordEmail: 'api/Account/SendForgotPasswordEmail',
    resetPassword: 'api/Account/ResetPassword',
    validateToken: 'api/Account/ValidateToken',
    validateForgotPasswordToken: 'api/Account/ValidateForgotPasswordToken',
    isUsernameExist: 'api/Account/IsUsernameExist',
    getAllLanguages: 'api/Account/GetAllLanguages',
    getUserListing: 'api/User/GetUsersListing',
    getRoles: 'api/User/GetRoles',
    saveUser: 'api/User/AddUser',
    getUserDetail: 'api/User/GetUsersListingById',
    getRoleListing: 'api/Role/GetRoles',
    addRole: 'api/Role/AddRole',
    deleteUser: 'api/User/DeleteUser',
    deleteRole: 'api/Role/DeleteRole',
    getTodoListing: 'api/Todo/GetTodoList',
    saveTodo: 'api/Todo/SaveTodo',
    deleteTodo: 'api/Todo/DeleteTodo',
    getTodoById: 'api/Todo/GetTodoById',
};

